USE customer_shopping_behavior;

SELECT * FROM customers limit 20;

-- Q1. What is the total revenue generated by male vs. female customers?

SELECT Gender, SUM(`Purchase Amount (USD)`) AS revenue 
FROM customers 
GROUP BY Gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT `Customer ID`, `Purchase Amount (USD)`
FROM customers
WHERE `Discount Applied` = 'Yes'
AND `Purchase Amount (USD)` >= (
    SELECT AVG(`Purchase Amount (USD)`)
    FROM customers
);


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT `Item Purchased`, ROUND(AVG(`Review Rating`), 2) AS `Average Product Rating`
FROM customers
GROUP BY `Item Purchased`
ORDER BY AVG(`Review Rating`) DESC
LIMIT 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT `Shipping Type`, 
       ROUND(AVG(`Purchase Amount (USD)`), 2) AS avg_amount
FROM customers
WHERE `Shipping Type` IN ('Standard', 'Express')
GROUP BY `Shipping Type`;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
SELECT `Subscription Status`,
       COUNT(`Customer ID`) AS total_customers,
       ROUND(AVG(`Purchase Amount (USD)`),2) AS avg_spend,
       ROUND(SUM(`Purchase Amount (USD)`),2) AS total_revenue
FROM customers
GROUP BY `Subscription Status`
ORDER BY total_revenue,avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT `Item Purchased`,
       ROUND(100.0 * SUM(CASE WHEN `Discount Applied` = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customers
GROUP BY `Item Purchased`
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT `Customer ID`, `Previous Purchases`,
CASE 
    WHEN `Previous Purchases` = 1 THEN 'New'
    WHEN `Previous Purchases` BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customers)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;


-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT Category,
           `Item Purchased`,
           COUNT(`Customer ID`) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY Category ORDER BY COUNT(`Customer ID`) DESC) AS item_rank
    FROM customers
    GROUP BY Category, `Item Purchased`
)
SELECT item_rank,Category, `Item Purchased`, total_orders
FROM item_counts
WHERE item_rank <=3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT `Subscription Status`,
       COUNT(`Customer ID`) AS repeat_buyers
FROM customers
WHERE `Previous Purchases` > 5
GROUP BY `Subscription Status`;

-- Q10. What is the revenue contribution of each age group? 
SELECT 
    Age,
    SUM(`Purchase Amount (USD)`) AS total_revenue
FROM customers
GROUP BY Age
ORDER BY total_revenue desc;
